# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: API

on:
  push:
    branches: [ "master" ]
    paths:
      - 'src/backend/**'
  pull_request:
    branches: [ "master" ]
    paths:
      - 'src/backend/**'

env:
  app-name: "who-is-where-api"
  rg-name: "who-is-where"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore
      working-directory: ./src/backend
    - name: Build
      run: dotnet build --no-restore
      working-directory: ./src/backend
    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: ./src/backend
    - name: Publish
      run: dotnet publish WhoIsWhere/WhoIsWhere.csproj -c Release -o api-build
      working-directory: ./src/backend
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3
      with:
        name: api
        path: ./src/backend/api-build/**
        if-no-files-found: error

  deploy:
    needs: build
    runs-on: ubuntu-latest

    environment:
      name: azure
      url: ${{ steps.deploywebapp.outputs.webapp-url }}

    steps:
    - name: Download a Build Artifact
      uses: actions/download-artifact@v3
      with:
        name: api
        path: api

    - name: Login via Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_API_CREDENTIALS }}

    - name: Deploy web app
      id: deploywebapp
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.app-name }}
        package: api

    - name: az cli logout
      run: az logout